In [220]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/train.csv')
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [221]:
df.isnull().any()

Id               False
MSSubClass       False
MSZoning         False
LotFrontage       True
LotArea          False
                 ...
MoSold           False
YrSold           False
SaleType         False
SaleCondition    False
SalePrice        False
Length: 81, dtype: bool

In [222]:
df.shape

(1460, 81)

#* PREPROCESSING*#

In [223]:
meanl=df['LotFrontage'].mean(skipna=True)

In [224]:
meanl

70.04995836802665

In [225]:
df['LotFrontage'].fillna(meanl,inplace=True)

In [226]:
df.isnull().any()

Id               False
MSSubClass       False
MSZoning         False
LotFrontage      False
LotArea          False
                 ...
MoSold           False
YrSold           False
SaleType         False
SaleCondition    False
SalePrice        False
Length: 81, dtype: bool

In [227]:
for i in df.isnull().sum():
  print(i)

0
0
0
0
0
0
1369
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
8
8
0
0
0
37
37
38
37
0
38
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
690
81
81
81
0
0
81
81
0
0
0
0
0
0
0
1453
1179
1406
0
0
0
0
0
0

In [228]:

null_counts = df.isnull().sum()
selected_columns = null_counts.loc[null_counts > 600]
selected_index = selected_columns.index
print(selected_columns)
print(selected_index)

Alley          1369
FireplaceQu     690
PoolQC         1453
Fence          1179
MiscFeature    1406
dtype: int64
Index(['Alley', 'FireplaceQu', 'PoolQC', 'Fence', 'MiscFeature'], dtype='object')

In [229]:
selected_index=selected_index.tolist()

In [230]:
selected_index

['Alley', 'FireplaceQu', 'PoolQC', 'Fence', 'MiscFeature']

In [231]:
a=[]
for i in range(0,len(df.columns)):
  if(df.columns[i] in selected_index):
    a.append(i)

In [232]:
a

[6, 57, 72, 73, 74]

In [233]:
df.drop(df.columns[a],axis=1,inplace=True)

In [234]:
df.isnull().any()

Id               False
MSSubClass       False
MSZoning         False
LotFrontage      False
LotArea          False
                 ...
MoSold           False
YrSold           False
SaleType         False
SaleCondition    False
SalePrice        False
Length: 76, dtype: bool

In [235]:

for i in df.isnull().sum():
  print(i)

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
8
8
0
0
0
37
37
38
37
0
38
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
81
81
81
0
0
81
81
0
0
0
0
0
0
0
0
0
0
0
0
0

In [236]:
for i in df.columns:
  if(df[i].dtype!='object'):
    meanl=df[i].mean(skipna=True)
    df[i].fillna(meanl,inplace=True)

In [237]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,...,0,0,0,0,0,12,2008,WD,Normal,250000

In [238]:
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()

In [239]:
for i in df.columns:
  if(df[i].dtype=='object'):
    df[i]=label_encoder.fit_transform(df[i])

In [240]:
for i in df.columns:
  if(df[i].dtype=='object'):
    df[i].fillna(method='ffill')

In [241]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,3,65.0,8450,1,3,3,0,4,...,0,0,0,0,0,2,2008,8,4,208500
1,2,20,3,80.0,9600,1,3,3,0,2,...,0,0,0,0,0,5,2007,8,4,181500
2,3,60,3,68.0,11250,1,0,3,0,4,...,0,0,0,0,0,9,2008,8,4,223500
3,4,70,3,60.0,9550,1,0,3,0,0,...,272,0,0,0,0,2,2006,8,0,140000
4,5,60,3,84.0,14260,1,0,3,0,2,...,0,0,0,0,0,12,2008,8,4,250000

In [242]:
df['LotConfig'].unique()

array([4, 2, 0, 1, 3])

In [243]:
df['MSZoning'].unique()

array([3, 4, 0, 1, 2])

In [244]:
df=df.fillna(method='bfill')

In [245]:
for i in df.isnull().sum():
    print(i)

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0

In [246]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 76 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   int64
 3   LotFrontage    1460 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   int64
 6   LotShape       1460 non-null   int64
 7   LandContour    1460 non-null   int64
 8   Utilities      1460 non-null   int64
 9   LotConfig      1460 non-null   int64
 10  LandSlope      1460 non-null   int64
 11  Neighborhood   1460 non-null   int64
 12  Condition1     1460 non-null   int64
 13  Condition2     1460 non-null   int64
 14  BldgType       1460 non-null   int64
 15  HouseStyle     1460 non-null   int64
 16  OverallQual    1460 non-null   int64
 17  OverallCond    1460 non-null   int64
 18  YearBuilt      1460 non-null   int64
 19  YearRemodAdd   1460 non-null   int64
 20  RoofStyle      1460 non-null   int64
 21  RoofMatl       1460 non-null   int64
 22  Exterior1st    1460 non-null   int64
 23  Exterior2nd    1460 non-null   int64
 24  MasVnrType     1460 non-null   int64
 25  MasVnrArea     1460 non-null   float64
 26  ExterQual      1460 non-null   int64
 27  ExterCond      1460 non-null   int64
 28  Foundation     1460 non-null   int64
 29  BsmtQual       1460 non-null   int64
 30  BsmtCond       1460 non-null   int64
 31  BsmtExposure   1460 non-null   int64
 32  BsmtFinType1   1460 non-null   int64
 33  BsmtFinSF1     1460 non-null   int64
 34  BsmtFinType2   1460 non-null   int64
 35  BsmtFinSF2     1460 non-null   int64
 36  BsmtUnfSF      1460 non-null   int64
 37  TotalBsmtSF    1460 non-null   int64
 38  Heating        1460 non-null   int64
 39  HeatingQC      1460 non-null   int64
 40  CentralAir     1460 non-null   int64
 41  Electrical     1460 non-null   int64
 42  1stFlrSF       1460 non-null   int64
 43  2ndFlrSF       1460 non-null   int64
 44  LowQualFinSF   1460 non-null   int64
 45  GrLivArea      1460 non-null   int64
 46  BsmtFullBath   1460 non-null   int64
 47  BsmtHalfBath   1460 non-null   int64
 48  FullBath       1460 non-null   int64
 49  HalfBath       1460 non-null   int64
 50  BedroomAbvGr   1460 non-null   int64
 51  KitchenAbvGr   1460 non-null   int64
 52  KitchenQual    1460 non-null   int64
 53  TotRmsAbvGrd   1460 non-null   int64
 54  Functional     1460 non-null   int64
 55  Fireplaces     1460 non-null   int64
 56  GarageType     1460 non-null   int64
 57  GarageYrBlt    1460 non-null   float64
 58  GarageFinish   1460 non-null   int64
 59  GarageCars     1460 non-null   int64
 60  GarageArea     1460 non-null   int64
 61  GarageQual     1460 non-null   int64
 62  GarageCond     1460 non-null   int64
 63  PavedDrive     1460 non-null   int64
 64  WoodDeckSF     1460 non-null   int64
 65  OpenPorchSF    1460 non-null   int64
 66  EnclosedPorch  1460 non-null   int64
 67  3SsnPorch      1460 non-null   int64
 68  ScreenPorch    1460 non-null   int64
 69  PoolArea       1460 non-null   int64
 70  MiscVal        1460 non-null   int64
 71  MoSold         1460 non-null   int64
 72  YrSold         1460 non-null   int64
 73  SaleType       1460 non-null   int64
 74  SaleCondition  1460 non-null   int64
 75  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(73)
memory usage: 867.0 KB

In [247]:
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,3,65.0,8450,1,3,3,0,4,...,0,0,0,0,0,2,2008,8,4,208500
1,2,20,3,80.0,9600,1,3,3,0,2,...,0,0,0,0,0,5,2007,8,4,181500
2,3,60,3,68.0,11250,1,0,3,0,4,...,0,0,0,0,0,9,2008,8,4,223500
3,4,70,3,60.0,9550,1,0,3,0,0,...,272,0,0,0,0,2,2006,8,0,140000
4,5,60,3,84.0,14260,1,0,3,0,2,...,0,0,0,0,0,12,2008,8,4,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,3,62.0,7917,1,3,3,0,4,...,0,0,0,0,0,8,2007,8,4,175000
1456,1457,20,3,85.0,13175,1,3,3,0,4,...,0,0,0,0,0,2,2010,8,4,210000
1457,1458,70,3,66.0,9042,1,3,3,0,4,...,0,0,0,0,2500,5,2010,8,4,266500
1458,1459,20,3,68.0,9717,1,3,3,0,4,...,112,0,0,0,0,4,2010,8,4,142125
1459,1460,20,3,75.0,9937,1,3,3,0,4,...,0,0,0,0,0,6,2008,8,4,147500

In [248]:
x=df.drop(['Id','SalePrice'],axis=1)
y=df['SalePrice']

In [249]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)

In [250]:
from sklearn.linear_model import LinearRegression
b=LinearRegression()
b.fit(x_train,y_train)
y_pred1=b.predict(x_test)

In [251]:
from sklearn.metrics import r2_score
ac=r2_score(y_pred1,y_test)

In [252]:
ac

0.7988358671532989

In [253]:
'''for i in df.columns:
  if(df[i].dtype=='object'):
    null_count = df[i].isnull().sum()
    if null_count > 0:
        random_samples = np.random.choice(df[i].dropna(), size=null_count)
        df[i][df[i].isnull()] = random_samples'''

"for i in df.columns:\n  if(df[i].dtype=='object'):\n    null_count = df[i].isnull().sum()\n    if null_count > 0:\n        random_samples = np.random.choice(df[i].dropna(), size=null_count)\n        df[i][df[i].isnull()] = random_samples"